---
- name: Operating System
  debug:
    msg:
      "Operating System Type   ": "{{ ansible_distribution }}"
      "Operating System Version": "{{ ansible_distribution_major_version }}"

- name: Run MacOSX Tasks
  import_tasks: macosx.yml
  when: (ansible_distribution == "MacOSX")

- name: Run Debian Tasks
  import_tasks: debian.yml
  when: (ansible_distribution == "Debian")

- name: Run RedHat Tasks
  import_tasks: redhat.yml
  when: (ansible_distribution == "RedHat")
