---
- name: Install Packages for RedHat
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  become: true
  become_user: root
  become_method: sudo
  with_items:
    - zsh
    - tmux
    - nano
    - vim
    - curl
    - wget
    - git
  tags: ['always', 'packages']
