---
- name: Basic usage
  ansible.builtin.debug:
    msg: "'{{ lookup('ansible.builtin.env', 'HOME') }}' is the HOME environment variable."

- name: Setting Facts
  ansible.builtin.set_fact:
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"

- name: Checking for previous installation of oh-my-zsh
  ansible.builtin.stat:
    path: "{{ home }}/.oh-my-zsh"
  register: ohmyzsh_check

- name: Installing oh-my-zsh from git
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ home }}/.oh-my-zsh"
  when: not ohmyzsh_check.stat.exists

- name: Installing zshrc
  ansible.builtin.copy:
    src: files/zshrc
    dest: "{{ home }}/.zshrc"

- name: Installing p10k.zsh
  ansible.builtin.copy:
    src: files/p10k.zsh
    dest: "{{ home }}/.p10k.zsh"
